# Generated by Django 5.2 on 2025-08-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.BigIntegerField(verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.BigIntegerField(verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Detailednews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hours', models.IntegerField(verbose_name='Часы')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hours', models.IntegerField(verbose_name='Часы')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='partners/', verbose_name='Партнеры')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('comment', models.TextField(verbose_name='Комменты')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2, verbose_name='Звездочки')),
            ],
        ),
    ]
