# Generated by Django 5.2.4 on 2025-08-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопросы')),
                ('answer', models.TextField(max_length=500, verbose_name='Ответы')),
            ],
            options={
                'db_table': 'FAQ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('rate', models.IntegerField(default=0.0)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Feedback',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя партнера')),
                ('image', models.ImageField(upload_to='images/partner/')),
            ],
            options={
                'db_table': 'partner',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Applications',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Detailednews',
        ),
        migrations.DeleteModel(
            name='Partners',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='news',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='news',
            name='img',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=1, upload_to='images/news/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterModelTable(
            name='news',
            table='News',
        ),
    ]
